In [2]:
import numpy as np
np.random.randint(0,10,size=(2,3))

array([[2, 1, 7],
       [6, 3, 1]])

In [7]:
np.random.seed(666)
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [8]:
np.random.random(size=(3,5))

array([[0.28116849, 0.46284169, 0.23340091, 0.76706421, 0.81995656],
       [0.39747625, 0.31644109, 0.15551206, 0.73460987, 0.73159555],
       [0.8578588 , 0.76741234, 0.95323137, 0.29097383, 0.84778197]])

In [11]:
np.random.normal(5,1,size=(3,5))

array([[5.20996833, 5.22958666, 5.26307642, 7.16633222, 3.95112407],
       [3.15231558, 5.53401503, 3.80425198, 4.71084263, 4.75667297],
       [4.25733347, 6.20790511, 6.02787711, 5.0573882 , 3.43996024]])

In [28]:
x=np.arange(10)
X=np.arange(15).reshape(3,5)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x=np.array([1,2,3])
y=np.array([3,2,1])
z=np.array([666,666,666])
print(np.concatenate([x,y,z]))
print(np.hstack([x,y,z]))

[  1   2   3   3   2   1 666 666 666]
[  1   2   3   3   2   1 666 666 666]


In [34]:
x=np.arange(10)
x1,x2,x3=np.split(x,[3,7])